import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
const code=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
function worker(){const handlers={},entries=new Map(),deleted=[];let skipped=false;const scope='https://example.com/Endless_2D.github.io/';const cache={addAll:async reqs=>{for(const r of reqs)entries.set(r.url,{url:r.url});},match:async key=>entries.get(key)};const context={URL,Request,fetch:async()=>{throw Error('offline');},caches:{open:async()=>cache,delete:async k=>deleted.push(k),keys:async()=>['unrelated',`endless2d:${scope}:old`]},self:{registration:{scope},addEventListener:(k,f)=>handlers[k]=f,clients:{matchAll:async()=>[]},skipWaiting:async()=>{skipped=true;}}};vm.runInNewContext(code,context);return{handlers,entries,deleted,context,skipped:()=>skipped};}
test('offline shell and modules resolve under GitHub Pages subpath',async()=>{const w=worker();let install;w.handlers.install({waitUntil:p=>install=p});await install;for(const path of ['','index.html','src/main.js','manifest.webmanifest','icons/icon-192.png']){let response;w.handlers.fetch({request:new Request('https://example.com/Endless_2D.github.io/'+path),respondWith:p=>response=p});assert.ok(await response);}let intercepted=false;w.handlers.fetch({request:new Request('https://example.com/other/'),respondWith:()=>intercepted=true});assert.equal(intercepted,false);});
test('activation cleans only this app caches and update refuses multiple clients',async()=>{const w=worker();let pending;w.handlers.activate({waitUntil:p=>pending=p});await pending;assert.equal(w.deleted.length,1);assert.ok(!w.deleted.includes('unrelated'));w.context.self.clients.matchAll=async()=>[{url:'https://example.com/Endless_2D.github.io/'},{url:'https://example.com/Endless_2D.github.io/index.html'}];let reply;w.handlers.message({data:{type:'ACTIVATE_WHEN_ALONE'},ports:[{postMessage:v=>reply=v}],waitUntil:p=>pending=p});await pending;assert.equal(reply,'BUSY');assert.equal(w.skipped(),false);});
test('manifest icons and every precache asset exist',()=>{const root=new URL('../',import.meta.url);const manifest=JSON.parse(fs.readFileSync(new URL('manifest.webmanifest',root)));assert.equal(manifest.scope,'./');for(const i of manifest.icons)assert.ok(fs.existsSync(new URL(i.src,root)));const assets=JSON.parse(code.match(/const ASSETS=(.*);/)[1]);for(const a of assets)assert.ok(fs.existsSync(new URL(a,root)));});
