import test from 'node:test';
import assert from 'node:assert/strict';
import { World } from '../src/world.js';
import { RunSave, SAVE_KEY, snapshot } from '../src/save.js';
function memory(){const map=new Map();return{getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k)};}
test('full boss run restores and follows identical future simulation',()=>{const storage=memory(),save=new RunSave(storage),a=new World();save.claim();a.time=90;for(let i=0;i<120;i++){a.player.invincible=1;a.update(1/60,{x:1,y:0});}assert.ok(save.write(a));const b=new World(),data=save.read();assert.ok(data);save.restore(b,data);assert.deepEqual(snapshot(a),snapshot(b));for(let i=0;i<50;i++){a.update(1/60,{x:0,y:1});b.update(1/60,{x:0,y:1});}assert.deepEqual(snapshot(a),snapshot(b));});
test('pending choices persist without reroll and remain paused',()=>{const save=new RunSave(memory()),a=new World();save.claim();a.gainXP(45);save.write(a);const b=new World();save.restore(b,save.read());assert.deepEqual(b.offers,a.offers);assert.equal(b.pendingChoices,3);const time=b.time;b.update(1,{x:1,y:0});assert.equal(b.time,time);});
test('death removes saved run but preserves other settings',()=>{const storage=memory(),save=new RunSave(storage),w=new World();storage.setItem('endless2d.best','999');save.claim();save.write(w);w.dead=true;w.player.hp=0;save.write(w);assert.equal(storage.getItem(SAVE_KEY),null);assert.equal(save.read(),null);assert.equal(storage.getItem('endless2d.best'),'999');});
test('bad saves and storage failures fail without throwing',()=>{const storage=memory();let errors=0;const save=new RunSave(storage,()=>errors++);storage.setItem(SAVE_KEY,'{broken');assert.equal(save.read(),null);storage.setItem(SAVE_KEY,JSON.stringify({version:99}));assert.equal(save.read(),null);assert.equal(errors,2);const denied=new RunSave({setItem:()=>{throw Error();}});assert.equal(denied.claim(),false);});
test('new tab takes ownership; old tab cannot resurrect a dead run',()=>{const storage=memory(),first=new RunSave(storage),second=new RunSave(storage),w=new World();first.claim();first.write(w);second.claim();w.dead=true;second.write(w);assert.equal(first.write(new World()),false);assert.equal(second.read(),null);});
